services:
  frontend:
    container_name: aquarismo-frontend
    build:
      context: ./frontend
    expose:
      - "4000"
    networks:
      - infra-vps_infra-net

networks:
  infra-net:
    external: true
